# Generated by Django 4.2 on 2023-04-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('reader_id', models.CharField(max_length=200)),
                ('time', models.CharField(default='None', max_length=300)),
            ],
        ),
    ]
